project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!assignments/"
    - "!data/"
    - "!images/"
    - "!old_materials/"
    - "!manual/"
    - "!slides/"

website:
  title: "BIOB470: Ornithology"
  navbar:
    right:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: default
    css: styles.css

